baseURL = "http://eatthisradio.com/"
languageCode = "en-us"
title = "Eat This Radio"
theme = "eatthisradio-2018"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-UK"
layoutdir = "layouts"
author = "Bastiaan Verhage"
pluralizelisttitles = false
publishDir = "public"
DefaultContentLanguage = "en"

[params]
dateform = "Jan 2, 2006"
copyright = "Eat This Radio 2018"

[mediaTypes]
[mediaTypes."text/json"]
suffix = "json"
